### PR TITLE
Support listening on any interface and fix threading bugs

### PR DESCRIPTION
**Pull request by BryanCrotaz**
- Listen IpAddress can now be `"*"`
- Fixed bug when receiving a large message in lots of small buffers - read bytes not necessarily equal to buffer size!
- Optimised read by reusing buffer
- Added semaphore around server writes to stop them overlapping (semaphore per client)
- Also supports query strings on incoming connection

### CODE REVIEW

**Comment by BryanCrotaz** [comment]
Also supports query strings on incoming connection

**Comment by jchristn** [comment]
Thanks so much @BryanCrotaz , I'll go through these by EOD tomorrow!  Appreciate your support and help on these!

**Comment by BryanCrotaz** [comment]
Tested on Windows, about to test on mono on Raspberry Pi

**Comment by jchristn** [comment]
Thank you @BryanCrotaz - I merged these in and created a new version (v1.1.0) due to the ClientConnected signature change - commit is here: https://github.com/jchristn/WatsonWebsocket/commit/a2a9599efe5aac030a1c77c7700133b6ff8ad3f0

And I updated NuGet with v1.1.0 as well: https://www.nuget.org/packages/WatsonWebsocket/1.1.0

Thank you very much for contributing these fixes and changes!

**Pull request merged**
