### PR TITLE
Make compliant with other web socket implementations

### PR DESCRIPTION
**Pull request by BryanCrotaz**
Remove length header to make it compatible with javascript and other implementations of websocket

### CODE REVIEW

**Comment by jchristn** [comment]
Hi @BryanCrotaz just merged these changes with modifications: https://github.com/jchristn/WatsonWebsocket/commit/d0c1831509b4d65f09334961f155af1f67de1c1f

Thanks for all of your help sir!

**Comment by BryanCrotaz** [comment]
It's now running the scoreboards at Lord's cricket ground in London :) - thanks!

**Comment by jchristn** [comment]
Oh, awesome!  That's huge!  Thanks @BryanCrotaz  :)

**Comment by BryanCrotaz** [comment]
2,700 sq ft huge...

**Comment by BryanCrotaz** [comment]
Right now there's 18,000 people watching your code here and a few million on Sky Sports

**Comment by jchristn** [comment]
Wow, that is pretty huge.  I'm glad it was able to meet the needs you guys had for it - was curious how you found the repo?  Cheers

**Comment by BryanCrotaz** [comment]
Google :)

**Pull request closed without merging**
